[supervisord]
nodaemon=true

[program:postfix]
command=/usr/sbin/postfix start-fg
autorestart=true
priority=10

[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true
priority=20

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=30

[program:php-fpm]
command=/usr/sbin/php-fpm8.1 -F
autorestart=true
priority=40
