site_name: OpenSec Lab — Documentacion
docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: orange
  features:
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.highlight
    - content.code.copy

nav:
  - Inicio: index.md
  - Escenarios:
    - Phishing: scenarios/phishing.md
  - Talleres:
    - Ataque y deteccion en APIs: workshops/api-breach.md
    - Guia de instructor (APIs): workshops/api-breach-instructor.md
    - Hacking Web y Deteccion: workshops/web-hacking.md
    - Guia de instructor (Web): workshops/web-hacking-instructor.md
    - Phishing y Robo de Credenciales: workshops/phishing.md
    - Guia de instructor (Phishing): workshops/phishing-instructor.md
  - Servicios:
    - DVWA: services/dvwa.md
    - Juice Shop: services/juiceshop.md
    - API Vulnerable: services/api.md
    - Wazuh SIEM: services/wazuh.md
    - GoPhish: services/gophish.md
    - Correo: services/mail.md
  - Cheat Sheets:
    - curl: cheatsheets/curl.md
    - nmap: cheatsheets/nmap.md
    - Burp Suite: cheatsheets/burp.md
    - Wazuh: cheatsheets/wazuh.md
