site_name: OpenSec Lab -- Documentacion
docs_dir: docs
site_dir: /site

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: orange
  features:
    - navigation.sections
    - navigation.top
    - search.highlight

nav:
  - Inicio: index.md
