server {
    listen 80;
    server_name _;

    root /html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # No cache para el portal (el sidecar lo regenera)
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    expires 0;
}
